### ISSUE TITLE
cyka blyat

### ISSUE THREAD

**Issue by dev** [zamabuvaraeu/IrcBot#5]
whos there

**Comment by SOUx4cx4fx56x69** [comment]
Сука блять

**Comment by SOUx4cx4fx56x69** [comment]
Давай пиздить его?

**Comment by SOUx4cx4fx56x69** [comment]
@zamabuvaraeu return your a bot to IRC2P blyat, i miss to you:p

**Comment by SOUx4cx4fx56x69** [comment]
Сука блять пиздец сука блять пиздец нахуй сука трясет от такойго пиздца сука а линукс версии всё нет сука где блять сука мы петицию напишем сука блять в ебанную сука по правам сука блять человека я блять сука напишу ебать и ты блять сука тебе блять прийдется сука блять делать сука блять линукс версию сука этой хуйни сука качай сука кросскомплитор и делай блять я блять сука блять желаю сука запускать больше ботов чем больше ботов тем больше выебонов и тем язык лучше и навыки программиста чей бот лучше и фрибескик будет блять темой если ты будешь добавлять сука на линукс сука в релиз сука блять файлик сука блять сука блять компилируй блять пожалуйста блять ебать

**Comment by SOUx4cx4fx56x69** [comment]
Ебать нахуй такой пиздец блять сделал сука парашу а на линукс не портировал, да тебе стоит ебло то разбить за такое норм пацаны делают норм версии ебать по пацански, да сука пацанская солидарность сука ты там блять кодекс вора знаешь то блять сука блят ькак ты в пидорашке живешь сука блять тогда если не деаелшь под линукс сука блять блять и кодыксы воров не знаешь это тебе не кодекс андерсонов читать там блять сука блять иррациональная хуйня блять без линукс версии

**Comment by SOUx4cx4fx56x69** [comment]
сука приходица под вайном дрочить твоего бота блять бсука блять сука блять сукаблтять

**Comment by SOUx4cx4fx56x69** [comment]
@zamabuvaraeu love you:P

**Comment by SOUx4cx4fx56x69** [comment]
@dev i there.

**Comment by zamabuvaraeu** [comment]
Заходи в IRC на chat.freenode.net на канал #s2ch
Я временно там обитаю.
